#!/bin/bash

# THIS FILE CONTAINS THE STEPS NEEDED TO AUTOMATICALLY UPDATE THE REPO ON A TAG CHANGE
# THIS FILE ITSELF MAY CHANGE FROM UPDATE TO UPDATE, SO WE CAN DYNAMICALLY FIX ANY ISSUES

# BY DEFAULT WE DON'T PROVIDE A SCRIPT TO AUTO RESTART MINERS - YOU'RE GOING TO HAVE TO WRITE YOUR OWN:
# ./restart_miners.sh

echo "Nothing to do!"