#!/bin/bash

# THIS FILE CONTAINS THE STEPS NEEDED TO AUTOMATICALLY UPDATE THE REPO ON A TAG CHANGE
# THIS FILE ITSELF MAY CHANGE FROM UPDATE TO UPDATE, SO WE CAN DYNAMICALLY FIX ANY ISSUES

# WE PROVIDE A DEFAULT SCRIPT FOR A PM2 PROCESS:
./relaunch_validator.sh $1
echo "Nothing to do!"